### ISSUE TITLE
下游任务训练

### ISSUE THREAD

**Issue by wpeak58** [ChenDdon/AGBTcode#3]
您好，关于下游任务的训练与预测，发现在代码中没有体现，请问，我该如何找到这些代码？谢谢

**Comment by ChenDdon** [comment]
您好，文档中的“Customize task-specific AGBT-FPs”小节，给出了以example为例，微调模型并得到feature的过程，例子中的任务是回归任务。如果进一步向将transformer用于分类问题及其微调过程，可见“Note”小节，我们更新了一个专门的库来介绍微调过程。

**Comment by ChenDdon** [comment]
你好，对于下游任务，文档中以example为例，给出了回归任务的继续训练的过程，见“Customize task-specific AGBT-FPs”小节。

**Comment by wpeak58** [comment]
您好，“Customize task-specific AGBT-FPs”，最后一步是feature_analysis.py 是对RF 的过程。没有涉及到下游任务。

**Comment by ChenDdon** [comment]
Hi,

We have provided all parameter settings for the downstream machine learning model in the "Downstream Machine Learning Algorithms" section of the supporting information. For these common models, we do not provide direct code.

Best wishes,
Dong
